### ISSUE TITLE
Only {snackF0,praatF0,shrF0,reaperF0,snackFormants,praatFormants,SHR} in opensauce

### ISSUE THREAD

**Issue by zlinsmile** [voicesauce/opensauce-python#39]
Excuses me,
It is so lucky that I can found this project,
But this is not finished?
Only support {snackF0,praatF0,shrF0,reaperF0,snackFormants,praatFormants,SHR} now?
And https://github.com/voicesauce/opensauce-python/tree/master/legacy is the old one with more function?

Thank you.

**Comment by terriyu** [comment]
The `legacy` folder is old code that doesn't work. The project is still under development and not finished. If the function is listed in the command line help, then it is supported. If not, then it is not supported.
