### ISSUE TITLE
Praat F0

### ISSUE THREAD

**Issue by k8si** [voicesauce/opensauce-python#4]
Implement the Praat F0 algorithm. See [func_PraatPitch](https://github.com/voicesauce/opensauce/blob/master/algos/functions/func_PraatPitch.m)

The complication here is that the Octave code actually opens the Praat application and uses Praat to make the calculations. While it'd be fine to do it this way from Python to start with, it might be nice/faster to port the algorithm that Praat uses to Python instead. This would be an interesting project for someone who has a good grasp on C++ (because that's what Praat is written in). 

The Praat source code is available [here](http://www.fon.hum.uva.nl/praat/download_sources.html)

**Comment by bendichter** [comment]
[Here](https://github.com/praat/praat/blob/ec624fdb82799972bd3c3485336a9af360b44528/fon/Sound_to_Pitch.cpp)'s the C++ implementation

**Comment by terriyu** [comment]
For now, we're just going to run Praat scripts to get this measurement.  This requires the user to download the Praat binary executable and specify the path to this executable on their machine.  Most of the Praat F0 functionality was implemented in commits [https://github.com/voicesauce/opensauce-python/commit/567bb751377356e99fec4d7da50949a0b76d3eae](https://github.com/voicesauce/opensauce-python/commit/567bb751377356e99fec4d7da50949a0b76d3eae) and [https://github.com/voicesauce/opensauce-python/commit/4f06602116ed5ba89fb054a12c99c33e4d2abcd2](https://github.com/voicesauce/opensauce-python/commit/4f06602116ed5ba89fb054a12c99c33e4d2abcd2)
